dub.json
1. UCS now specified for OS
2. Added OS X support (tested 27 and latest standard 34)
3. Removed `shared` versions. There is no reason to keep this flags on pyd side.
=> fix #3: dub configurations

dcompiler.py
-finline-functions is enabled by default at -O3
ldc doesn't have an inline flag. However, inlining definitely does occur at -O3
also, corrected -fverion to -d-version for ldc _releaseOptimizeOpts
=> fix gdc and ldc option syntax, remove finline-functions

docs/source/distutils.rst, support.py
I'm sure there are people out there who use it, but it really shouldn't be the default. Calling functions without parenthesis is now common in released D code.
=> -property is dead

dub.json
Those OS X paths are really not reliable. They've moved around across OS X versions and also many people use python installed in other directories (macports and homebrew).
=> add python3.5 and remove wrong OS X paths

infrastructure/pyd/ctor_wrap.d, infrastructure/pyd/func_wrap.d, infrastructure/pyd/make_object.d, infrastructure/pyd/references.d, infrastructure/util/typeinfo.d
it was deprecated, but now it's gone. Lead to completely misleading errors with the latest dmd beta, but this is the fix.
=> s/pointerTarget/PointerTarget/g due to pointerTarget being gone from phobos

dub.json
Works for a simple project on linux with python 3.6.  Arch linux has rolled version to 3.6.
=> update dub.json so works with python 3.6 on linux (and I hope windows - untested)

dcompiler.py
I tried to build examples/hello on Windows and immediately bumped into a problem with Python being installed in Program Files. The paths were quoted twice, so dmd was being invoked with arguments like
""c:\Program Files\...\smth.d"" 
and of course it complained about not knowing module Program (first word in Program Files).
Turns out if we don't try to quote the paths in dcompiler.py, then they are quoted later just once and everything starts to work fine, at least the example built and worked successfully.
=> Now works when Python path on Windows has spaces (Issue 52)

dcompiler.py
When building an extension, if some list of directories was provided in library_dirs parameter, then DCompiler.link() did not add the paths to Python libs (from _build_ext_library_dirs()).
=> Fix an issue with using other libs when building an extension on Windows

dub.json
It's not currently possible to build Python extensions using Microsoft's format for 32-bit. This PR fixes that.
=> Fix dub build with --arch=x86_mscoff

dub.json
Think systemwide python installation has been supported. Haven't made same change for python2 as unable to test but this should probably be done as well.
=> Add the location where python3 installs for all users

dub.json
It was needed because `dub` didn't apply `-fPIC` properly, but it has done for a decent long while now.
=> no more sourceLibrary

.travis.yml, README.md, appveyor.yml, dub.json, get_env_set_text.py, set_env_vars.bat, set_env_vars.sh
This enables people to control which version of pyd they are using in order to appropriately match the system without specifying endless configurations that reference subConfigurations that reference subConfigurations and so on...
This will make using pyd in larger dub package hierarchies significantly easier.
=> add env configuration

.travis.yml, dcompiler.py, envs/fedora28-ldc180-py36/Dockerfile, envs/jessie-dmd2_074-py34/Dockerfile, envs/run.sh, envs/stretch-gdc63-py37/Dockerfile, envs/ubuntu1604-ldc190-py35/Dockerfile, examples/misc/d_and_c/setup.py, examples/misc/gdc_sharedlibs/makefile, examples/misc/gdc_sharedlibs/so_ctor.c, examples/misc/gdc_sharedlibs/test1.d, runtests.sh
reimplement travis ci using docker
tests now cover python 2.7, 3.4, 3.5, 3.6, 3.7, and assorted versions of dmd, ldc and gdc
also, get gdc to build extensions again
=> Dockertests

dub.json
This commit fixes issue #113 which leads to linker errors when the username of a windows user contains spaces.
=> Fixing linker errors when $USERPROFILE contains spaces

infrastructure/deimos/python/pystate.d, infrastructure/deimos/python/pythonrun.d, infrastructure/deimos/python/sysmodule.d, infrastructure/deimos/python/unicodeobject.d
These two commits fix the wchar / wchar_t by importing the wchar_t from core.stdc.stddef
Fix for issue #111
=> Fixing wchar / wchar_t problems

infrastructure/pyd/make_object.d, tests/pyd_unittests/make_object/make_object.d
Fixes failed compilation occurring on DMD (v2.087.1) and LDC (1.16.0): `make_object.d(1293,13): Warning: statement is not reachable`
=> fix: SimpleFormatType static if 'statement is not reachable'

examples/dub/simple_embedded/dub.json
The dependency for pyd at /pyd/examples/dub/simple_embedded/dub.json needs to be updated.
Otherwise, one gets the error
The sub configuration directive "pyd" -> "python27" references a configuration that does not exists.
Could not resolve configuration for package simple_embedded
For the example, shared_embedded, this chage didn't work as the configuration python27-shared does not exists in the latest version of pyd. Please fix that also!
=> Updating the dependency on pyd. Fixes the build.

dub.json
Starting from python38 there is not python38m library.
See https://docs.python.org/3/whatsnew/3.8.html#build-and-c-api-changes
Before this Pull Request attempt to compile PyD on Ubuntu 20.04 causes following error:
```traceback
Performing "debug" build using /usr/bin/dmd for x86_64.
darg 0.1.0: target for configuration "library" is up to date.
tinyendian 0.2.0: target for configuration "library" is up to date.
dyaml 0.8.0: target for configuration "library" is up to date.
pyd ~master: target for configuration "python38" is up to date.
semver 0.3.2: target for configuration "library" is up to date.
termcolor-d 0.0.1: target for configuration "library" is up to date.
odoo-packager ~dev: building configuration "executable_py38"...
Linking...
/usr/bin/ld: cannot find -lpython3.8m
collect2: …
```
=> [FIX] Compilinng with python38 on posix system.

dub.json
The quoting insanity would be obsolete for DMD since v2.089 too.
The previous quotes for LDC only worked as long as there was no space in the path; e.g., `C:\Program Files (x86)\Python37-32\libs` led to a linker error (`LNK1104: cannot open file '"\LIBPATH:C:\Program Files (x86)\Python37-32\libs".obj'`).
=> dub.json: Fix /LIBPATH linker flags for LDC builds on Windows

setup/pyd_set_env_vars.sh
Turns out some other script of ours that `source`s this also uses the same idiom for figuring out the location of the script. Same names, too! Making the variables readonly revealed this problem.
=> Use a function to avoid polluting/overwriting envvars

setup/pyd_set_env_vars.sh
Need to egg my face, I introduced a bug in https://github.com/ariovistus/pyd/pull/148/ - forgot to pass arguments down from the script to the main function. I made untested edits in that PR ("what's the worst that could happen?"); this time I tested this carefully.
Took the opportunity to make a few improvements that make the script more robust:
- the shebang line avoids inadvertently running the script in a separate shell, otherwise it would appear to run successfully but have no effect
- `main` has a random suffix so as to avoid clashing with some other `main` in the current environment
- replaced the test `-z $1` with `$# -eq 0` because if the calling environment has `set -u`, it would fail on account of unset variable
- quoted strings as https://www.shellcheck.net indicated, on the …
=> Fixup following bug introduced in #148

infrastructure/pyd/make_object.d
This reverts commit d18d388b1bbf4ba9e50fec6e49087c13a40a2d6c.
This fixes this compilation error:
```
pyd/infrastructure/pyd/func_wrap.d(802,22): Error: cannot implicitly convert expression `fn` of type `RangeWrapper* function() return` to `RangeWrapper* function()`
pyd/infrastructure/pyd/func_wrap.d-mixin-405(407,33): Error: template instance `pyd.func_wrap.dg_wrapper!(RangeWrapper*, RangeWrapper* function() return)` error instantiating
pyd/infrastructure/pyd/func_wrap.d(364,19):        instantiated from here: `memberfunc_to_func!(RangeWrapper*, iter)`
pyd/infrastructure/pyd/class_wrap.d(311,48):        instantiated from here: `method_wrap!(RangeWrapper*, iter, "RangeWrapper.__iter__")`
pyd/infrastructure/pyd/class_wrap.d(1580,22):        instantiated from here: `call!("RangeWrapper", …
```
=> Revert "Fix another deprecation wrt. escaping `this`"

dub.json
Hi,
Please, accept this PR to add support for Python 3.11, because it is default version of python for Ubuntu 23.04.
Thanks)
PS: Please, do not forget to publish new release after merge.
=> Added configuration to use Python 3.11
